import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
      test.setTimeout(200000);

  import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Calendar button - choose date' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '18' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Calendar button - choose date' }).nth(1).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '4' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Columns' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ErpQuoteNum' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ErpQuoteNum' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'NREPrice' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'PanelLength' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Columns' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'PartNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '10000034466' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '10000034466' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '-500246-001 (ARRAY)' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '-500246-001 (ARRAY)' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '3322206-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '3322206-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).fill('311032');
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'U1-311032FAB' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'U1-311032FAB' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'PartNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'PartNumber' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'QuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231130-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231130-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231130-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231205-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).fill('G231121-0001');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231121-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'G231121-' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'QuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'CustomerName' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '24M Technologies-Indianapolis' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ABB France' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'A And M Electronics, Inc.' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).fill('3G Wireless');
  await page.locator('iframe').contentFrame().getByRole('option', { name: '3G Wireless' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '3G Wireless' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'CustomerName' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . FILTER' }).click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Customer', exact: true }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Customer', exact: true }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Part Number' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Part Number' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'RFQNum' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'NWI 00907 RFQ' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'RFQNum' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'ErpQuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Search' }).fill('');
  await page.locator('iframe').contentFrame().getByRole('option', { name: '10001' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '10016' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'ErpQuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Facility' }).locator('i').click();
  await page.locator('iframe').contentFrame().locator('#slicer-dropdown-popup-489de007-fe4f-acd6-bdef-b174f286ce59').getByRole('option', { name: 'SNA' }).locator('div span').click();
  await page.locator('iframe').contentFrame().locator('#slicer-dropdown-popup-489de007-fe4f-acd6-bdef-b174f286ce59').getByRole('option', { name: 'SNA' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Facility' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Facility' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'ErpQuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'ErpQuoteNumber' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Class2' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'N', exact: true }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Class2' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'SalesRep' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Angelica Castaneda' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Abigail Reyna' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'SalesRep' }).locator('i').click();
  await page.locator('iframe').contentFrame().locator('visual-container:nth-child(29) > transform > .visualContainer > .visualContent > .vcBody > .visualWrapper > visual-modern > .visual > .slicer-container > .slicer-content-wrapper > .date-slicer > .date-slicer-slider > .noUi-target > .noUi-base > div:nth-child(2) > .noUi-handle > .noUi-touch-area').click();
  await page.locator('iframe').contentFrame().locator('visual-container:nth-child(29) > transform > .visualContainer > .visualContent > .vcBody > .visualWrapper > visual-modern > .visual > .slicer-container > .slicer-content-wrapper > .date-slicer > .date-slicer-slider > .noUi-target > .noUi-base > .noUi-connects > .noUi-connect').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'QuoteQTY' }).click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'QuoteQTY' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().locator('.slicer-container.focused > .slicer-content-wrapper > .date-slicer > .date-slicer-slider > .noUi-target > .noUi-base > div:nth-child(3) > .noUi-handle > .noUi-touch-area').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('Start').fill('10');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('End').fill('500000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartUnitPrice' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Category' }).locator('i').click();
  await page.locator('iframe').contentFrame().locator('#slicer-dropdown-popup-c525124a-5f01-7f6c-f324-3ba3ba4d9075 > .slicer-dropdown-content > .slicerContainer > .slicerBody > .scroll-wrapper > .scrollbar-inner > .scrollRegion > .visibleGroup > div:nth-child(2) > .slicerItemContainer > .slicerCheckbox > .glyphicon').click();
  await page.locator('iframe').contentFrame().locator('#slicer-dropdown-popup-c525124a-5f01-7f6c-f324-3ba3ba4d9075 > .slicer-dropdown-content > .slicerContainer > .slicerBody > .scroll-wrapper > .scrollbar-inner > .scrollRegion > .visibleGroup > div:nth-child(2) > .slicerItemContainer > .slicerCheckbox > .glyphicon').click();
  await page.locator('iframe').contentFrame().locator('#slicer-dropdown-popup-c525124a-5f01-7f6c-f324-3ba3ba4d9075 > .slicer-dropdown-content > .slicerContainer > .slicerBody > .scroll-wrapper > .scrollbar-inner > .scrollRegion > .visibleGroup > div:nth-child(2) > .slicerItemContainer > .slicerCheckbox > .glyphicon').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Category' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Class3' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Class3' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelLength' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelLength' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelLength' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelLength' }).getByLabel('End').fill('3000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('Start').fill('0.001');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('End').fill('180');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelWidth' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('End').fill('25000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartLength' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PanelUp/Array' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartLength' }).getByLabel('End').fill('30000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartLength' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartWidth' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartWidth' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartWidth' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'PartWidth' }).getByLabel('End').fill('13000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('Start').fill('0.001');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('End').fill('70000');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'TotalPanel' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LayerCount' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LayerCount' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LayerCount' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LayerCount' }).getByLabel('End').fill('50');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LamCycles' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LamCycles' }).getByLabel('Start').fill('2');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LamCycles' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'LamCycles' }).getByLabel('End').fill('10');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'MicroVias' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'MicroVias' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'MicroVias' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'MicroVias' }).getByLabel('End').fill('4500');
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Material' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Megtron' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Material' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'SurfaceFinish1' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ENIG' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ENIG' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'SurfaceFinish2' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'SurfaceFinish2' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Spacing' }).click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Spacing' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Thickness', exact: true }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Thickness', exact: true }).getByLabel('Start').fill('10');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Thickness', exact: true }).getByLabel('End').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'Thickness', exact: true }).getByLabel('End').fill('2500');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('Start').click();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('Start').fill('0.001');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness1' }).getByLabel('End').fill('3500');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('Start').fill('0.001');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'GoldThickness2' }).getByLabel('End').fill('100');
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Ormet Connections' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Ormet Connections' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Ormet Connections' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Ormet Connections' }).getByLabel('End').fill('10');
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('Start').fill('0.001');
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('Start').fill('1');
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: '# Of Resistor Layers' }).getByLabel('End').fill('10');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('Start').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('Start').fill('50');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('End').dblclick();
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('End').fill('75');
  await page.locator('iframe').contentFrame().getByRole('group', { name: 'ResistorOhm' }).getByLabel('End').press('Enter');
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Search').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . FILTER' }).click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . FILTER' }).click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Clear').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Clear').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
});